name: Build and deploy Node.js app to Azure Web App - shapecrafthackathon-frontend

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: FrontEnd/package-lock.json

      - name: Install dependencies
        working-directory: ./FrontEnd
        run: npm ci --legacy-peer-deps

      - name: Rebuild native modules for Linux
        working-directory: ./FrontEnd
        run: npm rebuild lightningcss --force

      - name: Build Next.js app
        working-directory: ./FrontEnd
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p publish
          cp -r FrontEnd/.next publish/.next
          cp -r FrontEnd/public publish/public
          cp FrontEnd/package.json publish/
          cp FrontEnd/next.config.js publish/ || true
          cp FrontEnd/tsconfig.json publish/ || true
          cp FrontEnd/.env.production publish/.env.production || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0EF51C7C3D00438F81F9AC1F755B65B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CFA2902651D44426B999819E48EEBAFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3F78303978244D6F88AB6E5CAB85ADB1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shapecrafthackathon'
          slot-name: 'Production'
          package: ./publish


