name: Build and Deploy ASP.Net Core App to Azure Web App - shapecraftbackend

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish app
        working-directory: ./backend/Demo.ShapeCraftAPI
        run: dotnet publish -c Release -o ../../publish_output

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE71A4D17B3549A8B4883F62023CCB0B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8778086FE6624F40BD4CB9F51342B2BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BC93054D8F64AD6A49ABE78CA73D7E9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shapecraftbackend'
          slot-name: 'Production'
          package: ./publish_output

